### ISSUE TITLE
strace: |autoreset: Broken pipe

### ISSUE THREAD

**Issue by ypawar159** [SpellFoundry/avrdude-rpi#3]
Hello,
I get this error every time I upload the hex file. Though hex file is uploaded successfully to Arduino.
Here is the complete output:
`arduinoud ASCIITable.ino.hex` 
done with autoreset
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe

avrdude-original: AVR device initialized and ready to accept instructions
avrdude-original: Device signature = 0x1e950f
avrdude-original: NOTE: "flash" memory has been specified, an erase cycle will be performed
                  To disable this feature, specify the -D option.
avrdude-original: erasing chip
avrdude-original: reading input file "ASCIITable.ino.hex"
avrdude-original: writing flash (1920 bytes):
avrdude-original: 1920 bytes of flash written

avrdude-original: safemode: Fuses OK (E:00, H:00, L:00)
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe
strace: |autoreset: Broken pipe

avrdude-original done.  Thank you.

strace: |autoreset: Broken pipe

**arduinoud** is single line bash script which invokes the avrdude with hex file as parameter.

**Comment by LEMAOR** [comment]
got the same and after fiddling around, i just ended giving permissions to the auto reset file

**Comment by arunderwood** [comment]
I'm running into this issue as well.  Could someone please clarify how they fixed it?

**Comment by arunderwood** [comment]
@ypawar159 @LEMAOR do you have any more details on a resolution?

**Comment by zagatta-sonah** [comment]
I have the same problem. Anybody fixed it yet? 
@arunderwood @LEMAOR  @ypawar159

**Comment by arunderwood** [comment]
I never got it working.

My _"fix"_ was to switch to PlatformIO for flashing the SleepyPi.  I PR'ed support for the SleepyPi reset pin into their implementation of AVRDude so you don't need to implement this workaround if your using PIO.  PlatformIO does some other good stuff like dependency management and CI/CD support so it's been nice overall.

If you want a reference for PlatformIO and SleepyPi, I've got it working on a project.  Don't mind the mess, it's a work in progress.
* https://github.com/arunderwood/iphotrod-arduino/blob/master/platformio.ini
* https://github.com/arunderwood/iphotrod-arduino/blob/master/Makefile

**Comment by rin67630** [comment]
me too.
It works anyway, so not a big issue, just beautifying.

**Comment by ypawar159** [comment]
I am no longer involved in this. So closing the issue.
